Allow overriding of secret keys for database
TeamPiped/Piped-Kubernetes pull request #78
Opened 2024-01-23 16:01 UTC by gmemstr

I currently use the the [CrunchyData Postgres Operator](https://github.com/CrunchyData/postgres-operator) in my cluster, which provisions secrets for PostgreSQL users with the username and password. These contain keys that cannot be modified (from what I can tell), so this change allows the value to be overridden.

Before:

```yaml
secret: postgres-connection-details
```

After:

```yaml
secret:
  name: postgres-connection-details
  username: user
  password: pass
```

2024-01-23 16:18 UTC, samip5 requested changes
Change log annotation is missing from Chart.yaml at least.

2024-01-23 16:19 UTC, samip5 commented
Also this should be a major bump, due to incompatible backwards compatibility if one uses that secret definition like I actually do.

2024-01-23 17:31 UTC, gmemstr commented
Good point, will update!

2024-01-24 05:55 UTC, samip5 requested changes
Lint failure: Error: 102:14 [trailing-spaces] trailing spaces

2024-01-24 10:49 UTC, merged

2024-01-26 09:40 UTC, samip5 commented
@gmemstr Are you aware of these errors?

```
Error: template: piped/templates/backend/configmap.yaml:68:64: executing "piped/templates/backend/configmap.yaml" at <.Values.backend.config.database.secret.name>: can't evaluate field name in type interface {}
```

When secret is defined, but the optional things are not?